-- | GENERATED by oracle/haskell-prim.hs from oracle/haskell-prim.txt,
-- | by asking GHC 9.10 and Tidal's Sound.Tidal.UI. Do not edit; regenerate.
module Tidal.Conformance.HaskellGolden (golden) where

golden :: Array { input :: String, output :: String }
golden =
  [ { input: "quotRem 7 2", output: "(3,1)" }
  , { input: "quotRem -7 2", output: "(-3,-1)" }
  , { input: "quotRem 7 -2", output: "(-3,1)" }
  , { input: "quotRem -7 -2", output: "(3,-1)" }
  , { input: "quotRem 6 -3", output: "(-2,0)" }
  , { input: "divMod 7 2", output: "(3,1)" }
  , { input: "divMod -7 2", output: "(-4,1)" }
  , { input: "divMod 7 -2", output: "(-4,-1)" }
  , { input: "divMod -7 -2", output: "(3,-1)" }
  , { input: "divMod -6 3", output: "(-2,0)" }
  , { input: "quotRem -1180591620717411303427 36893488147419103233", output: "(-31,-36893488147419103204)" }
  , { input: "divMod -1180591620717411303427 36893488147419103233", output: "(-32,29)" }
  , { input: "divMod 1180591620717411303427 -36893488147419103233", output: "(-32,-29)" }
  , { input: "gcd -12 18", output: "6" }
  , { input: "gcd 0 0", output: "0" }
  , { input: "gcd 0 -5", output: "5" }
  , { input: "int 9223372036854775807", output: "9223372036854775807" }
  , { input: "int 9223372036854775808", output: "-9223372036854775808" }
  , { input: "int -9223372036854775809", output: "9223372036854775807" }
  , { input: "int 18446744073709551621", output: "5" }
  , { input: "intAdd 9223372036854775807 1", output: "-9223372036854775808" }
  , { input: "intSub -9223372036854775808 1", output: "9223372036854775807" }
  , { input: "intMul 4294967296 4294967296", output: "0" }
  , { input: "intMul 3037000500 3037000500", output: "-9223372036709301616" }
  , { input: "intMod -7 2", output: "1" }
  , { input: "intMod 7 -2", output: "-1" }
  , { input: "intMod -9223372036854775808 -1", output: "0" }
  , { input: "shiftL 1 63", output: "-9223372036854775808" }
  , { input: "shiftL 1 64", output: "0" }
  , { input: "shiftL 3 62", output: "-4611686018427387904" }
  , { input: "shiftL -1 13", output: "-8192" }
  , { input: "shiftR -1 17", output: "-1" }
  , { input: "shiftR -9223372036854775808 1", output: "-4611686018427387904" }
  , { input: "shiftR 9223372036854775807 62", output: "1" }
  , { input: "xorwise 0", output: "0" }
  , { input: "xorwise 1", output: "270369" }
  , { input: "xorwise -1", output: "253983" }
  , { input: "xorwise 536870911", output: "136356051423263" }
  , { input: "xorwise 9223372036854775807", output: "-9221190605785014241" }
  , { input: "xorwise -9223372036854775808", output: "-9221190605785268224" }
  , { input: "show 10/4", output: "5 % 2" }
  , { input: "show -10/4", output: "(-5) % 2" }
  , { input: "show 10/-4", output: "(-5) % 2" }
  , { input: "show 0/7", output: "0 % 1" }
  , { input: "add 1/3 1/6", output: "1 % 2" }
  , { input: "sub 1/3 1/2", output: "(-1) % 6" }
  , { input: "mul -2/3 9/4", output: "(-3) % 2" }
  , { input: "div 1/3 -2/9", output: "(-3) % 2" }
  , { input: "compare 1/3 2/7", output: "GT" }
  , { input: "compare -1/3 -2/7", output: "LT" }
  , { input: "properFraction 7/2", output: "(3,1 % 2)" }
  , { input: "properFraction -7/2", output: "(-3,(-1) % 2)" }
  , { input: "properFraction 1/3", output: "(0,1 % 3)" }
  , { input: "properFraction -1/3", output: "(0,(-1) % 3)" }
  , { input: "truncate -7/2", output: "-3" }
  , { input: "floor -7/2", output: "-4" }
  , { input: "floor 7/2", output: "3" }
  , { input: "ceiling -7/2", output: "-3" }
  , { input: "ceiling 7/2", output: "4" }
  , { input: "round 5/2", output: "2" }
  , { input: "round 7/2", output: "4" }
  , { input: "round -5/2", output: "-2" }
  , { input: "round -7/2", output: "-4" }
  , { input: "round 1/2", output: "0" }
  , { input: "round -1/2", output: "0" }
  , { input: "round 13/10", output: "1" }
  , { input: "round -13/10", output: "-1" }
  , { input: "timeToIntSeed 0/1", output: "0" }
  , { input: "timeToIntSeed 1/3", output: "160169040429" }
  , { input: "timeToIntSeed 1/8", output: "59224798924" }
  , { input: "timeToIntSeed 299/1", output: "136809985312507" }
  , { input: "timeToIntSeed 300/1", output: "0" }
  , { input: "timeToIntSeed 301/7", output: "20662650110142" }
  , { input: "timeToIntSeed -1/3", output: "160169351699" }
  , { input: "timeToIntSeed 123456789/1000", output: "71401709822968" }
  , { input: "timeToIntSeed 1000000007/3", output: "16827742597205" }
  , { input: "timeToRand 0/1", output: "268435456" }
  , { input: "timeToRand 1/3", output: "181508653" }
  , { input: "timeToRand 1/8", output: "168998604" }
  , { input: "timeToRand 5/4", output: "149701169" }
  , { input: "timeToRand 299/1", output: "244549371" }
  , { input: "timeToRand 301/7", output: "99319998" }
  , { input: "timeToRand -1/3", output: "181819923" }
  , { input: "timeToRand 123456789/1000", output: "26010616" }
  , { input: "timeToRand 1000000007/3", output: "60731477" }
  , { input: "parsec stringAlt ab", output: "Right \"ab\"" }
  , { input: "parsec stringAlt ax", output: "Left (line 1, column 1):\nunexpected \"x\"\nexpecting \"ab\"" }
  , { input: "parsec stringAlt q", output: "Left (line 1, column 1):\nunexpected \"q\"\nexpecting \"ab\" or \"ax\"" }
  , { input: "parsec tryStringAlt ax", output: "Right \"ax\"" }
  , { input: "parsec digitsEof 123", output: "Right \"123\"" }
  , { input: "parsec digitsEof 12a", output: "Left (line 1, column 3):\nunexpected 'a'\nexpecting digit or end of input" }
  , { input: "parsec digitsEof _", output: "Left (line 1, column 1):\nunexpected \" \"\nexpecting digit" }
  , { input: "parsec lookAheadThen abc", output: "Right \"abc\"" }
  , { input: "parsec lookAheadThen abd", output: "Left (line 1, column 1):\nunexpected \"d\"\nexpecting \"abc\"" }
  , { input: "parsec commaList a,bc,d", output: "Right [\"a\",\"bc\",\"d\"]" }
  , { input: "parsec commaList a,,b", output: "Left (line 1, column 3):\nunexpected \",\"\nexpecting letter" }
  , { input: "parsec labelled x", output: "Right 'x'" }
  , { input: "parsec labelled 7", output: "Right '7'" }
  , { input: "parsec labelled q", output: "Left (line 1, column 1):\nunexpected \"q\"\nexpecting an x or digit" }
  , { input: "parsec column __^_^x", output: "Right (1,17)" }
  , { input: "parsec column ^^", output: "Right (1,17)" }
  , { input: "parsec keyword let", output: "Right \"let\"" }
  , { input: "parsec keyword lets", output: "Left (line 1, column 5):\nunexpected 's'" }
  , { input: "parsec keyword le", output: "Left (line 1, column 1):\nunexpected end of input\nexpecting \"let\"" }
  , { input: "parsec spacesThen __abc", output: "Right \"abc\"" }
  , { input: "parsec spacesThen __", output: "Left (line 1, column 3):\nunexpected end of input\nexpecting space or letter" }
  , { input: "parsec optionDigits 42", output: "Right \"42\"" }
  , { input: "parsec optionDigits x", output: "Left (line 1, column 1):\nunexpected 'x'\nexpecting digit or end of input" }
  , { input: "parsec choiceStrings bar", output: "Right \"bar\"" }
  , { input: "parsec choiceStrings fob", output: "Left (line 1, column 1):\nunexpected \"b\"\nexpecting \"foo\"" }
  , { input: "parsec choiceStrings zzz", output: "Left (line 1, column 1):\nunexpected \"z\"\nexpecting \"foo\" or \"bar\"" }
  , { input: "throughDouble 1/10", output: "3602879701896397 % 36028797018963968" }
  , { input: "throughDouble -1/10", output: "(-3602879701896397) % 36028797018963968" }
  , { input: "throughDouble 9/16", output: "9 % 16" }
  , { input: "throughDouble 1/3", output: "6004799503160661 % 18014398509481984" }
  , { input: "throughDouble 2/3", output: "6004799503160661 % 9007199254740992" }
  , { input: "throughDouble 0/1", output: "0 % 1" }
  , { input: "throughDouble 9007199254740993/1", output: "9007199254740992 % 1" }
  , { input: "throughDouble 9007199254740995/1", output: "9007199254740996 % 1" }
  , { input: "throughDouble 1/10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", output: "20240225330731 % 202402253307310618352495346718917307049556649764142118356901358027430339567995346891960383701437124495187077864316811911389808737385793476867013399940738509921517424276566361364466907742093216341239767678472745068562007483424692698618103355649159556340810056512358769552333414615230502532186327508646006263307707741093494784" }
  , { input: "throughDouble 1/1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", output: "0 % 1" }
  , { input: "throughDouble 3/404804506614621236704990693437834614099113299528284236713802716054860679135990693783920767402874248990374155728633623822779617474771586953734026799881477019843034848553132722728933815484186432682479535356945490137124014966849385397236206711298319112681620113024717539104666829230461005064372655017292012526615415482186989568", output: "1 % 101201126653655309176247673359458653524778324882071059178450679013715169783997673445980191850718562247593538932158405955694904368692896738433506699970369254960758712138283180682233453871046608170619883839236372534281003741712346349309051677824579778170405028256179384776166707307615251266093163754323003131653853870546747392" }
  , { input: "throughDouble 1/404804506614621236704990693437834614099113299528284236713802716054860679135990693783920767402874248990374155728633623822779617474771586953734026799881477019843034848553132722728933815484186432682479535356945490137124014966849385397236206711298319112681620113024717539104666829230461005064372655017292012526615415482186989568", output: "0 % 1" }
  , { input: "throughDouble 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368/1", output: "179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368 % 1" }
  , { input: "throughDouble 179769313486231580793728971405303415079934132710037826936173778980444968292764750946649017977587207096330286416692887910946555547851940402630657488671505820681908902000708383676273854845817711531764475730270069855571366959622842914819860834936475292719074168444365510704342711559699508093042880177904174497792/1", output: "179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216 % 1" }
  , { input: "throughDouble 10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000/1", output: "179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216 % 1" }
  , { input: "throughDouble 123456789012345678901/1", output: "123456789012345683968 % 1" }
  ]
