// Ask Haskell Tidal what every corpus case means, and write the answers as
// src/Tidal/Conformance/TidalGolden.purs, so every column holds the engine
// to Tidal without GHCi present.
//
// Needs a GHCi running Tidal behind Limulus's server (http://localhost:3036,
// or ORACLE_URL). Each case is rendered with oracle/render.hs, the same
// form Tidal.Conformance renders in. A case GHCi refuses is recorded as
// refused, and purerl-tidal must refuse it too.
//
//   node engine/core/oracle/generate.mjs

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const here = fileURLToPath(new URL(".", import.meta.url));
const root = join(here, "..");
const url = process.env.ORACLE_URL || "http://localhost:3036";

const ghci = async (block) => {
  const r = await fetch(`${url}/api/ghci/eval`, { method: "POST", body: block });
  return r.json();
};

const cases = (await readFile(join(here, "corpus.txt"), "utf8"))
  .split("\n")
  .filter((l) => l.trim() && !l.startsWith("#"))
  .map((l) => {
    const [, from, to, expr] = l.match(/^(\S+)\s+(\S+)\s+(.*)$/);
    return { from: Number(from), to: Number(to), expr };
  });

const loaded = await ghci(`:script ${join(here, "render.hs")}`);
if (!loaded.ok) throw new Error(`render.hs did not load: ${loaded.out}`);

const version = (await ghci("putStrLn tidal_version")).out.trim();
const golden = [];
for (const c of cases) {
  const r = await ghci(`render (${c.expr}) ${c.from} ${c.to}`);
  golden.push({ ...c, events: r.ok ? JSON.parse(r.out) : null });
  if (!r.ok) console.log(`refused by Tidal: ${c.expr}`);
}

const str = (s) => JSON.stringify(s);
const row = (g) =>
  `  { expr: ${str(g.expr)}, from: ${g.from}, to: ${g.to}\n    , events: ${
    g.events === null ? "Nothing" : `Just [ ${g.events.map(str).join(", ")} ]`
  } }`;

await writeFile(
  join(root, "src/Tidal/Conformance/TidalGolden.purs"),
  `-- | GENERATED by oracle/generate.mjs from oracle/corpus.txt, by
-- | asking Haskell Tidal ${version} in GHCi. Do not edit; regenerate.
-- |
-- | \`events\` are as oracle/render.hs renders them; \`Nothing\` means Tidal
-- | refused the expression.
module Tidal.Conformance.TidalGolden (tidalVersion, golden) where

import Data.Maybe (Maybe(..))

tidalVersion :: String
tidalVersion = ${str(version)}

golden :: Array { expr :: String, from :: Int, to :: Int, events :: Maybe (Array String) }
golden =
  [
${golden.map(row).join(",\n")}
  ]
`,
);
console.log(`${golden.length} cases from Tidal ${version}`);
