-- Ask GHC (and Tidal's own Sound.Tidal.UI) what every case in
-- haskell-prim.txt is, and print src/Tidal/Conformance/HaskellGolden.purs.
-- From engine/core: `make oracle-prim` in purerl-tidal runs it.
import Data.Bits (shiftL, shiftR)
import Text.Parsec hiding (count)
import Text.Parsec.String (Parser)
import Data.List (intercalate)
import Data.Ratio ((%))
import Sound.Tidal.UI (timeToIntSeed, timeToRand, xorwise)
import System.Info (compilerVersion)
import Data.Version (showVersion)

int :: String -> Int
int = fromInteger . read

integer :: String -> Integer
integer = read

rational :: String -> Rational
rational s = let (n, _ : d) = break (== '/') s in read n % read d

eval :: [String] -> String
eval ["quotRem", a, b] = show (quotRem (integer a) (integer b))
eval ["divMod", a, b] = show (divMod (integer a) (integer b))
eval ["gcd", a, b] = show (gcd (integer a) (integer b))
eval ["int", a] = show (int a)
eval ["intAdd", a, b] = show (int a + int b)
eval ["intSub", a, b] = show (int a - int b)
eval ["intMul", a, b] = show (int a * int b)
eval ["intMod", a, b] = show (int a `mod` int b)
eval ["shiftL", a, n] = show (int a `shiftL` read n)
eval ["shiftR", a, n] = show (int a `shiftR` read n)
eval ["xorwise", a] = show (xorwise (int a))
eval ["show", r] = show (rational r)
eval ["add", r, s] = show (rational r + rational s)
eval ["sub", r, s] = show (rational r - rational s)
eval ["mul", r, s] = show (rational r * rational s)
eval ["div", r, s] = show (rational r / rational s)
eval ["compare", r, s] = show (compare (rational r) (rational s))
eval ["properFraction", r] = show (properFraction (rational r) :: (Integer, Rational))
eval ["truncate", r] = show (truncate (rational r) :: Integer)
eval ["floor", r] = show (floor (rational r) :: Integer)
eval ["ceiling", r] = show (ceiling (rational r) :: Integer)
eval ["round", r] = show (round (rational r) :: Integer)
eval ["timeToIntSeed", r] = show (timeToIntSeed (rational r))
-- Exact: every value is k / 2^29, so print k.
eval ["timeToRand", r] = show (truncate ((timeToRand (rational r) :: Double) * 536870912) :: Integer)
eval ["parsec", name, input] = parsec name (map unescape input)
  where
    unescape '^' = '\t'
    unescape '_' = ' '
    unescape c = c
eval c = error ("unknown case: " ++ unwords c)

-- The same table as Tidal.Conformance's.
parsec :: String -> String -> String
parsec name input = case name of
  "stringAlt" -> run (string "ab" <|> string "ax")
  "tryStringAlt" -> run (try (string "ab") <|> string "ax")
  "digitsEof" -> run (many1 digit <* eof)
  "lookAheadThen" -> run (lookAhead (string "ab") *> string "abc")
  "commaList" -> run (sepBy (many1 letter) (char ',') <* eof)
  "labelled" -> run ((char 'x' <?> "an x") <|> digit)
  "column" -> run (many (oneOf " \t") *> ((\p -> (sourceLine p, sourceColumn p)) <$> getPosition))
  "keyword" -> run (string "let" <* notFollowedBy alphaNum)
  "spacesThen" -> run (spaces *> many1 letter <* eof)
  "optionDigits" -> run (option "none" (many1 digit) <* eof)
  "choiceStrings" -> run (choice [string "foo", string "bar"] <* eof)
  _ -> error ("unknown parser: " ++ name)
  where
    run :: Show a => Parser a -> String
    run p = show (parse p "" input)

main :: IO ()
main = do
  cases <- filter (\l -> not (null l) && take 1 l /= "#") . lines <$> getContents
  let row c = "{ input: " ++ show c ++ ", output: " ++ show (eval (words c)) ++ " }"
  putStr $ unlines
    [ "-- | GENERATED by oracle/haskell-prim.hs from oracle/haskell-prim.txt,"
    , "-- | by asking GHC " ++ showVersion compilerVersion ++ " and Tidal's Sound.Tidal.UI. Do not edit; regenerate."
    , "module Tidal.Conformance.HaskellGolden (golden) where"
    , ""
    , "golden :: Array { input :: String, output :: String }"
    , "golden ="
    , "  [ " ++ intercalate "\n  , " (map row cases)
    , "  ]"
    ]
